// Mock data for development (will be replaced with real Supabase data later)

export const mockUser = {
  id: '1',
  name: 'Alex',
  email: 'alex@fittrack.com',
  streak: 14,
  level: 12,
  xp: 850,
  xpToNextLevel: 1000,
}

export const mockNextWorkout = {
  id: '1',
  name: 'Pull Day',
  programName: 'Push Pull Legs',
  estimatedDuration: 60,
  currentDay: 5,
  totalDays: 6,
  allExercises: [
    { name: 'Weighted Pull-ups', sets: 3 },
    { name: 'Barbell Rows', sets: 4 },
    { name: 'Face Pulls', sets: 3 },
    { name: 'Bicep Curls', sets: 3 },
    { name: 'Hammer Curls', sets: 3 },
  ],
}

export const mockWeeklyStats = {
  workouts: 4,
  workoutsChange: '+2',
  totalTime: '4.2h',
  avgTime: '~63 min/session',
  personalRecords: 3,
  xpEarned: 850,
  levelProgress: 73,
}

export const mockRecentActivity = [
  {
    id: '1',
    name: 'Push Day',
    daysAgo: 2,
    duration: 58,
    xp: 150,
    achievements: [
      { type: 'pr', name: 'Bench Press' },
      { type: 'pr', name: 'Dips' },
    ],
  },
  {
    id: '2',
    name: 'Leg Day',
    daysAgo: 3,
    duration: 62,
    xp: 180,
    achievements: [{ type: 'badge', name: '🏆 Leg Legend' }],
  },
]

export const mockLatestAchievement = {
  id: '1',
  emoji: '🏆',
  name: 'Two Week Warrior',
  description: 'Complete 14 consecutive days',
  nextAchievement: 'Three Week Champion',
  progress: 14,
  goal: 21,
  progressPercentage: 67,
}

// Workout Execution Mock Data
export const mockWorkoutExecution = {
  id: '1',
  name: 'Push Day',
  startedAt: new Date().toISOString(),
  currentExerciseIndex: 1, // 0-based, so this is exercise 2
  exercises: [
    {
      id: '1',
      name: 'Barbell Bench Press',
      category: 'Compound',
      muscleGroup: 'Chest',
      videoUrl: null,
      sets: [
        {
          id: '1',
          setNumber: 1,
          type: 'warmup',
          targetWeight: 135,
          targetReps: 10,
          lastWeight: 135,
          lastReps: 10,
          completed: true,
          actualWeight: 135,
          actualReps: 10,
          rpe: null,
        },
        {
          id: '2',
          setNumber: 2,
          type: 'working',
          targetWeight: 225,
          targetReps: { min: 8, max: 10, type: 'range' },
          lastWeight: 225,
          lastReps: 8,
          personalRecord: { weight: 235, reps: 8 },
          completed: false,
          actualWeight: null,
          actualReps: null,
          rpe: null,
        },
        {
          id: '3',
          setNumber: 3,
          type: 'working',
          targetWeight: 225,
          targetReps: { type: 'failure' },
          lastWeight: 225,
          lastReps: 7,
          completed: false,
          actualWeight: null,
          actualReps: null,
          rpe: null,
        },
      ],
      currentSetIndex: 1, // Currently on set 2
      restTime: 300, // 5 minutes in seconds
    },
    {
      id: '2',
      name: 'Incline Dumbbell Press',
      category: 'Compound',
      muscleGroup: 'Chest',
      videoUrl: null,
      sets: [
        {
          id: '4',
          setNumber: 1,
          type: 'working',
          targetWeight: 80,
          targetReps: { min: 8, max: 12, type: 'range' },
          lastWeight: 75,
          lastReps: 10,
          completed: false,
        },
        {
          id: '5',
          setNumber: 2,
          type: 'working',
          targetWeight: 80,
          targetReps: { min: 8, max: 12, type: 'range' },
          lastWeight: 75,
          lastReps: 9,
          completed: false,
        },
      ],
      currentSetIndex: 0,
      restTime: 180,
    },
    {
      id: '3',
      name: 'Cable Flyes',
      category: 'Isolation',
      muscleGroup: 'Chest',
      videoUrl: null,
      sets: [
        {
          id: '6',
          setNumber: 1,
          type: 'working',
          targetWeight: 40,
          targetReps: { min: 12, max: 15, type: 'range' },
          lastWeight: 40,
          lastReps: 13,
          completed: false,
        },
        {
          id: '7',
          setNumber: 2,
          type: 'working',
          targetWeight: 40,
          targetReps: { min: 12, max: 15, type: 'range' },
          lastWeight: 40,
          lastReps: 12,
          completed: false,
        },
      ],
      currentSetIndex: 0,
      restTime: 90,
    },
    {
      id: '4',
      name: 'Tricep Pushdowns',
      category: 'Isolation',
      muscleGroup: 'Triceps',
      videoUrl: null,
      sets: [
        {
          id: '8',
          setNumber: 1,
          type: 'working',
          targetWeight: 60,
          targetReps: { min: 10, max: 12, type: 'range' },
          lastWeight: 55,
          lastReps: 11,
          completed: false,
        },
        {
          id: '9',
          setNumber: 2,
          type: 'working',
          targetWeight: 60,
          targetReps: { min: 10, max: 12, type: 'range' },
          lastWeight: 55,
          lastReps: 10,
          completed: false,
        },
      ],
      currentSetIndex: 0,
      restTime: 90,
    },
    {
      id: '5',
      name: 'Overhead Tricep Extension',
      category: 'Isolation',
      muscleGroup: 'Triceps',
      videoUrl: null,
      sets: [
        {
          id: '10',
          setNumber: 1,
          type: 'working',
          targetWeight: 50,
          targetReps: { min: 12, max: 15, type: 'range' },
          lastWeight: 50,
          lastReps: 14,
          completed: false,
        },
        {
          id: '11',
          setNumber: 2,
          type: 'working',
          targetWeight: 50,
          targetReps: { min: 12, max: 15, type: 'range' },
          lastWeight: 50,
          lastReps: 13,
          completed: false,
        },
      ],
      currentSetIndex: 0,
      restTime: 90,
    },
  ],
}
